### ISSUE TITLE
Time Knot Spell Server Crash

### ISSUE THREAD

**Issue by Spacewalker98** [WinDanesz/AncientSpellcraft#14]
As from the title im playing on a server and discovered the spell then used it and kept getting internal server errors, the problem seems to occur when the potion effect wears off and the solution is to just spam clear potion effect in the console and this is recreatable, not sure if there is any thing else i need to post if so let me know, thank you in advance.

**Comment by WinDanesz** [comment]
Hi, if you have access to the error log, that would be very useful

**Comment by Spacewalker98** [comment]
new to all this so lmk if theres more that you need
[crash-2021-02-22_14.57.22-client.txt](https://github.com/WinDanesz/AncientSpellcraft/files/6041696/crash-2021-02-22_14.57.22-client.txt)
hope it helps in some way

**Comment by WinDanesz** [comment]
This issue should be fixed in AncientSpellcraft-1.1.2, you are using AncientSpellcraft-1.1.1. If try to update to the server and the clients to the latest version if you can. If that is not an option for now, edit the player's NBT data to remove the time knot potion effect from it, and disable this spell in the ebwiz config file.

**Comment by WinDanesz** [comment]
Should be fixed in 1.1.3:
https://www.curseforge.com/minecraft/mc-mods/ancient-spellcraft/files/3238582
If you are still seeing any crashes with Time Knot, please open a new Issue
