### ISSUE TITLE
Possession spellbook duplication with gravestones

### ISSUE THREAD

**Issue by oozeyyy** [WinDanesz/AncientSpellcraft#23]
Modpack: MC Eternal 1.4.1 with Corails Tombstone mod

https://youtu.be/jfU-n8Pypw8

**Comment by WinDanesz** [comment]
Hello, this issue is about a spell of the main Electroblob's Wizardry mod and not the Ancient Spellcraft addon's content. Please open this issue on Eb's tracker so that he can see it: https://github.com/Electroblob77/Wizardry/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BGive+a+brief%2C+relevant+title+here%5D
